const typeCast = {
  integer: 'INTEGER',
  int: 'INTEGER',
  int4: 'INTEGER',
  bigint: 'BIGINT',
  int8: 'BIGINT',
  smallint: 'SMALLINT',
  int2: 'SMALLINT',
  decimal: 'DECIMAL',
  numeric: 'NUMERIC',
  real: 'REAL',
  float4: 'REAL',
  doublePrecision: 'DOUBLE PRECISION',
  float8: 'DOUBLE PRECISION',
  serial: 'SERIAL',
  bigSerial: 'BIGSERIAL',
  smallSerial: 'SMALLSERIAL',
  text: 'TEXT',
  varchar: 'VARCHAR',
  characterVarying: 'CHARACTER VARYING',
  char: 'CHAR',
  character: 'CHARACTER',
  charInternal: 'CHAR INTERNAL',
  timestamp: 'TIMESTAMP',
  timestamptz: 'TIMESTAMP WITH TIME ZONE',
  timestampWithTimeZone: 'TIMESTAMP WITH TIME ZONE',
  date: 'DATE',
  time: 'TIME',
  timetz: 'TIME WITH TIME ZONE',
  timeWithTimeZone: 'TIME WITH TIME ZONE',
  interval: 'INTERVAL',
  boolean: 'BOOLEAN',
  bool: 'BOOLEAN',
  bytea: 'BYTEA',
  inet: 'INET',
  cidr: 'CIDR',
  macAddr: 'MACADDR',
  macAddr8: 'MACADDR8',
  point: 'POINT',
  line: 'LINE',
  lSeg: 'LINE SEGMENT',
  lineSegment: 'LINE SEGMENT',
  box: 'BOX',
  path: 'PATH',
  polygon: 'POLYGON',
  circle: 'CIRCLE',
  json: 'JSON',
  jsonb: 'JSONB',
  uuid: 'UUID',
  int4Range: 'INT4RANGE',
  int8Range: 'INT8RANGE',
  numRange: 'NUMRANGE',
  tsRange: 'TSRANGE',
  tstZRange: 'TSTZRANGE',
  dateRange: 'DATERANGE',
  integerArray: 'INTEGER[]',
  bigintArray: 'BIGINT[]',
  smallintArray: 'SMALLINT[]',
  textArray: 'TEXT[]',
  varcharArray: 'VARCHAR[]',
  charArray: 'CHAR[]',
  timestampArray: 'TIMESTAMP[]',
  dateArray: 'DATE[]',
  timeArray: 'TIME[]',
  booleanArray: 'BOOLEAN[]',
  byteaArray: 'BYTEA[]',
  jsonArray: 'JSON[]',
  jsonbArray: 'JSONB[]',
  uuidArray: 'UUID[]',
} as const;

type TypeCastKeys = keyof typeof typeCast;
